name: "Bug 报告 🐛"
description: "提交 ReinaManager 的 Bug"
title: "🐛[Bug] "
labels:
  - bug

body:

  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug 报告

        请确保：
        - 问题确实存在
        - 可以提供复现步骤
        - 提供足够信息帮助定位


  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: |
        请详细描述遇到的问题。
    validations:
      required: true


  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: |
        请提供可以复现问题的步骤。
      value: |
        1.
        2.
        3.
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: 日志信息
      description: |
        如果有错误日志，请粘贴。
      render: shell


  - type: input
    id: version
    attributes:
      label: 程序版本
      description: |
        请填写版本号或 Commit Hash。
    validations:
      required: true


  - type: dropdown
    id: os
    attributes:
      label: 系统环境
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true


  - type: textarea
    id: screenshot
    attributes:
      label: 截图


  - type: checkboxes
    id: confirmation
    attributes:
      label: 提交确认
      options:

        - label: |
            <sub>
            我确认已经阅读模板，并提供真实有效的信息。
            如果该 Issue 无意义、重复、无法复现或无法帮助定位问题，
            我接受维护者直接关闭该 Issue。
            </sub>
          required: true