//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::FromJsonQueryResult;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// BGM 授权信息。
///
/// 旧手动 token 只有 access_token；OAuth 登录会包含 refresh_token 和 expires_at。
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(default)]
pub struct BgmAuth {
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub expires_at: Option<i64>,
    pub username: Option<String>,
    pub nickname: Option<String>,
}

/// Hikarinagi OIDC/PKCE 授权信息。
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(default)]
pub struct HikarinagiAuth {
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub expires_at: Option<i64>,
    pub user_id: Option<i64>,
    pub name: Option<String>,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub bgm_auth: Option<BgmAuth>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hikarinagi_auth: Option<HikarinagiAuth>,
    #[sea_orm(column_type = "Text", nullable)]
    pub vndb_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub save_root_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub db_backup_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub install_root_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub le_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub magpie_path: Option<String>,
}

impl Model {
    pub fn save_root_path_value(&self) -> Option<&str> {
        self.save_root_path.as_deref()
    }

    pub fn db_backup_path_value(&self) -> Option<&str> {
        self.db_backup_path.as_deref()
    }

    #[cfg(target_os = "windows")]
    pub fn le_path_value(&self) -> Option<&str> {
        self.le_path.as_deref()
    }

    #[cfg(target_os = "windows")]
    pub fn magpie_path_value(&self) -> Option<&str> {
        self.magpie_path.as_deref()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
